=== ARMmbed/mbed-os/tools/config/schema_app.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "title": "Mbed Library Schema",
  "description": "Configuration file for an mbed library",
  "type": "object",
  "$id": "http://example.com/root.json",
  "properties": {
    "name": {
      "$ref": "file:definitions.json#/name_definition"
    },
    "config": {
      "$ref": "file:definitions.json#/config_definition"
    },
    "target_overrides": {
      "$ref": "file:definitions.json#/target_overrides_definition"
    },
    "macros": {
      "$ref": "file:definitions.json#/macro_definition"
    },
    "artifact_name": {
      "type": "string"
    }
  },
  "additionalProperties": false
}

=== ARMmbed/mbed-os/rtos/source/TARGET_CORTEX/mbed_lib.json
{
    "name": "rtos",
    "config": {
        "present": 1,
         "main-thread-stack-size": {
            "help": "The size of the main thread's stack",
            "value": 4096
         },
         "timer-thread-stack-size": {
            "help": "The size of the timer thread's stack",
            "value": 768
         },
         "idle-thread-stack-size": {
            "help": "The size of the idle thread's stack",
            "value": 512
         },
         "thread-stack-size": {
            "help": "The default stack size of new threads",
            "value": 4096
         },
         "idle-thread-stack-size-tickless-extra": {
            "help": "Additional size to add to the idle thread when a specific target or application implementation requires it or in case tickless is enabled and LPTICKER_DELAY_TICKS is used",
            "value": 256
         },
         "idle-thread-stack-size-debug-extra": {
            "help": "Additional size to add to the idle thread when code compilation optimisation is disabled",
            "value": 0
         },
         "thread-num": {
            "help": "Maximum number of CMSIS-RTOSv2 object-pool threads that can be active at the same time",
            "value": 0
         },
         "thread-user-stack-size": {
            "help": "The total memory available for all CMSIS-RTOSv2 object-pool thread stacks combined",
            "value": 0
         },
         "timer-num": {
            "help": "Maximum number of CMSIS-RTOSv2 object-pool timers that can be active at the same time",
            "value": 0
         },
         "evflags-num": {
            "help": "Maximum number of CMSIS-RTOSv2 object-pool event flag objects that can be active at the same time",
            "value": 0
         },
         "mutex-num": {
            "help": "Maximum number of CMSIS-RTOSv2 object-pool mutexes that can be active at the same time",
            "value": 0
         },
         "semaphore-num": {
            "help": "Maximum number of CMSIS-RTOSv2 object-pool semaphores that can be active at the same time",
            "value": 0
         },
         "msgqueue-num": {
            "help": "Maximum number of CMSIS-RTOSv2 object-pool message queues that can be active at the same time",
            "value": 0
         },
         "msgqueue-data-size": {
            "help": "The total memory available for all CMSIS-RTOSv2 object-pool message queues combined",
            "value": 0
         }
    },
    "macros": ["_RTE_"],
    "target_overrides": {
        "*": {
            "target.boot-stack-size": "0x400"
        },
        "STM": {
            "idle-thread-stack-size-debug-extra": 128
        },
        "STM32L1": {
            "idle-thread-stack-size-debug-extra": 512
        },
        "STM32F070RB": {
            "main-thread-stack-size": 3072
        },
        "STM32F072RB": {
            "main-thread-stack-size": 3072
        },
        "MCU_NRF51": {
            "target.boot-stack-size": "0x800"
        },
        "MCU_NRF52840": {
            "target.boot-stack-size": "0x800"
        },
        "MCU_NRF52832": {
            "target.boot-stack-size": "0x800"
        },
        "MCU_NRF51_UNIFIED": {
            "target.boot-stack-size": "0x800"
        },
        "NUVOTON": {
            "idle-thread-stack-size-debug-extra": 512
        }
    }
}

=== ARMmbed/mbed-os/connectivity/libraries/ppp/mbed_lib.json
{
    "name": "ppp",
    "macros": ["NSAPI_PPP_AVAILABLE=(MBED_CONF_PPP_ENABLED || MBED_CONF_LWIP_PPP_ENABLED)"],    
    "config": {
        "enabled": {
            "help": "Enable support for PPP interfaces",
            "value": false
        },
        "ipv4-enabled": {
            "help": "Enable support for ipv4 PPP interface",
            "value": true
        },
        "ipv6-enabled": {
            "help": "Enable support for ipv6 PPP interface",
            "value": false
        },
        "debug": {
            "help": "Enable debug traces for PPP",
            "value": false,
            "macro_name": "PPP_DEBUG"
        },
        "enable-trace": {
            "help": "Enable PPP packet traces (traces every outbound and inbound packet)",
            "value": false
        },
        "thread-stacksize": {
            "help": "Thread stack size for PPP",
            "value": 816
        },
        "mbed-event-queue": {
            "help": "Use mbed event queue instead of PPP thread",
            "value": false
        }
    },
    "target_overrides": {
        "RZ_A1XX": {
            "thread-stacksize": 896
        },
        "RZ_A2XX": {
            "thread-stacksize": 896
        },
        "CY8CPROTO_062_4343W": {
            "thread-stacksize": 896
        },
        "CY8CKIT_062_WIFI_BT": {
            "thread-stacksize": 896
        },
        "CY8CKIT_062S2_43012": {
            "thread-stacksize": 896
        },
        "CYSBSYSKIT_01": {
            "thread-stacksize": 896
        }
    }
}

=== ARMmbed/mbed-os/connectivity/FEATURE_BLE/source/cordio/mbed_lib.json
{
    "name": "cordio",
    "macros": ["WSF_MS_PER_TICK=1"],
    "config": {
        "max-connections": {
            "help": "Maximum number of connections",
            "value": 3,
            "macro_name": "DM_CONN_MAX"
        },
        "max-syncs": {
            "help": "Maximum number of periodic advertising synchronizations",
            "value": 1,
            "macro_name": "DM_SYNC_MAX"
        },
        "max-advertising-sets": {
            "help": "Number of supported advertising sets: must be set to 1 for legacy advertising",
            "value": 3,
            "macro_name": "DM_NUM_ADV_SETS"
        },
        "max-phys": {
            "help": "Number of scanner and initiator PHYs (LE 1M, LE 2M and LE Coded): must be set to 1 for legacy scanner and initiator",
            "value": 3,
            "macro_name": "DM_NUM_PHYS"
        },
        "max-l2cap-channels": {
            "help": "Maximum number of connection oriented channels",
            "value": 1,
            "macro_name": "L2C_COC_CHAN_MAX"
        },
        "max-l2cap-clients": {
            "help": "Maximum number of connection oriented channel registered clients",
            "value": 1,
            "macro_name": "L2C_COC_REG_MAX"
        },
        "max-att-writes": {
            "help": "Maximum number of simultaneous ATT write commands",
            "value": 1,
            "macro_name": "ATT_NUM_SIMUL_WRITE_CMD"
        },
        "max-att-notifications": {
            "help": "Maximum number of simultaneous ATT notifications",
            "value": 1,
            "macro_name": "ATT_NUM_SIMUL_NTF"
        },
        "max-smp-devices": {
            "help": "Max number of devices in the security database",
            "value": 3,
            "macro_name": "SMP_DB_MAX_DEVICES"
        },
        "desired-att-mtu": {
            "help": "Desired ATT_MTU, this needs to be between 23 and 517 (inclusive). The effective ATT_MTU is limited by rx-acl-buffer-size (minus 4 bytes for the header).",
            "value": 23
        },
        "rx-acl-buffer-size": {
            "help": "Size of the buffer holding the reassembled complete ACL packet. This will limit the effective ATT_MTU (to its value minus 4 bytes for the header). The size of the buffer must be small enough to be allocated from the existing cordio pool. If this value is increased you may need to adjust the memory pool.",
            "value": 70
        },
        "max-prepared-writes": {
            "help": "Number of queued prepare writes supported by server.",
            "value": 4
        },
        "cmac-calculation": {
            "help": "Where the CBC MAC calculatio is performed. Valid values are 0 (host) and 1 (controller through HCI).",
            "value": 1,
            "macro_name": "SEC_CCM_CFG"
        },
        "route_unhandled_command_complete_events": {
            "help": "If enabled the stack will forward to the user all HCI events not handled by the stack.",
            "value": 1
        },
        "preferred-tx-power": {
            "help": "Preferred value of tx power in dbm (-128,127). This value is not guaranteed and relies on existing support in the HCI driver.",
            "value": 0
        },
        "max-eatt-channels": {
            "help": "Maximum number of EATT channels per DM connection.",
            "value": 1,
            "macro_name": "EATT_CONN_CHAN_MAX"
        },
        "rpa-swap-workaround": {
            "help": "Check connection complete event if it needs the addresses swapped due to bug in controller",
            "value": null,
            "macro_name": "CORDIO_RPA_SWAP_WORKAROUND"
        }
    },
    "target_overrides": {
        "NUCLEO_WB55RG": {
            "rpa-swap-workaround": true
        }
    }
}

=== ARMmbed/mbed-os/connectivity/drivers/ble/FEATURE_BLE/TARGET_NORDIC/TARGET_NORDIC_CORDIO/TARGET_NRF5x/mbed_lib.json
{
    "name": "cordio-nordic-ll",
    "config": {
        "zero-copy-hci": {
            "help": "messages sent between Host and Controller are passed directly without copying if enabled. WSF messages ownership is trasfered to the callee.",
            "value": 1,
            "macro_name": "CORDIO_ZERO_COPY_HCI"
        },
        "hci-driver-buffer-size": {
            "help": "Defines the memory to be allocated by the NRFCordiHciDriver.",
            "value": 12500
        },
        "wsf-pool-buffer-size": {
            "help": "Defines the memory allocated for the wsf memory pool.",
            "value": 4900
        }
    },
    "target_overrides": {
        "MCU_NRF52840": {
            "hci-driver-buffer-size": 16056
        }
    },
    "macros": [
        "INIT_BROADCASTER",
        "INIT_OBSERVER",
        "INIT_CENTRAL",
        "INIT_PERIPHERAL",
        "INIT_ENCRYPTED",
        "LHCI_ENABLE_VS=0",
        "BB_CLK_RATE_HZ=1000000",
        "LL_MAX_PER_SCAN=3"
    ]
}
